#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"
dir=`pwd`
echo $dir

find -type f -print0 | egrep -zZ -v -e '(\.git($|\/.*)|^./setup$|host_specific)' | xargs -0 -n1 -i ln -snf $dir/{} ~/{}

mkdir -p ~/.backup
